//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainEX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainEX()
        {
            this.LetterEXes = new HashSet<LetterEX>();
            this.SubEXes = new HashSet<SubEX>();
        }
    
        public int Id { get; set; }
        public int noletter { get; set; }
        public System.DateTime datecome { get; set; }
        public string Code { get; set; }
        public string sidecome { get; set; }
        public Nullable<System.DateTime> dateletter { get; set; }
        public string description { get; set; }
        public string respons { get; set; }
        public Nullable<System.DateTime> datefolow { get; set; }
        public Nullable<int> noIn { get; set; }
        public Nullable<System.DateTime> dateIn { get; set; }
        public string sideIn { get; set; }
        public string recevied { get; set; }
        public string notes { get; set; }
        public string noout1 { get; set; }
        public Nullable<System.DateTime> dateprevletter { get; set; }
        public string useradd { get; set; }
        public Nullable<System.DateTime> dateadd { get; set; }
        public string usermod { get; set; }
        public Nullable<System.DateTime> datemod { get; set; }
        public Nullable<System.DateTime> DateMode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterEX> LetterEXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubEX> SubEXes { get; set; }
    }
}
