//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Side
    {
        public int Ser { get; set; }
        public string Side1 { get; set; }
    }
}
